export const Strings = {
    sign_In:'Sign In',
    login:'Sign In',
    accessYourAccount:'Access to your account',
    Or:'Or',
    loginWithEmail:'Sign In with email address',
    loginWithMobile:'Sign In with mobile number',
    verification:'Verification',
    resend:'Resend',
    otpVerificationText:'Please Enter the 4 Digit Code Sent To',
    phoneNumber : "Phone Number",
    emailAddress :'Email Address',
    verify:'Verify',
    chooseYourService:"Choose Your Service",
    forgotPassword:' Forgot Password?',
    forgotReceiveVerification:"Please Enter Your Email Address To Receive a Verification Code.",
    send:'Send',
    setNewPassword:'Set New Password',
    yourNewPasswordDifferent:"Your New Password Must Be Different from Previously Used Password.",
    save:'Save',
    continue:'Continue',
    TellUsLoveAbout :'Tell us what you love about the app, or what we could be doing better.'
}