import { StyleSheet, Dimensions } from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { 
  
   fonts,
  //  latoFonts 
  } from '../../../theme/fonts/fonts';
  import { 
    colors
    } from '../../../theme/colors';
import { RFValue } from 'react-native-responsive-fontsize';
const restuarantStyles = StyleSheet.create({
  menuScreenConatiner: {
    flex: 1,
    backgroundColor: 'white',
  },
  headerConatiner: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: hp('2%'),
    paddingHorizontal: hp('2%'),
    width: wp('100%'),
    alignItems: 'center',
  },
  backArrowStyle: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: '1.5%',
  },
  seachBarStyle: {
    backgroundColor: 'white',
    width: wp('30%'),
    marginRight: hp('2%'),
    padding: hp('0.8%'),
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    shadowOffset: { width: -2, height: 4 },
    shadowColor: '#171717',
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  searchText: {
    fontSize: RFValue(12),
    fontFamily: fonts.regular,
    marginLeft: '5%',
  },
  optionStyle: {
    height: 30,
    width: 30,
    padding: hp('0.5%'),
    borderRadius: 8,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: -2, height: 4 },
    shadowColor: '#171717',
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  dotConatiner: {
    width: wp('100%'),
    height: hp('100%'),
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  crossIcon: {
    marginBottom: hp('2%'),
    backgroundColor: 'black',
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    alignSelf: 'center',
  },
  dotModalConatiner: {
    width: wp('100%'),
    height: hp('25%'),
    backgroundColor: '#fff',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    // paddingBottom: '5%',
  },
  dotItemName: {
    marginBottom: hp('3%'),
    fontSize: RFValue(16),
    fontFamily: fonts.medium,
  },
  likeText: {
    fontSize: RFValue(16),
    fontFamily: fonts.regular,
    marginLeft: hp('1%'),
    color: 'black',
  },
  offerListConatiner: {
    justifyContent: 'space-evenly',
    marginRight: 10,
    padding: 5,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#0D71CD',
    backgroundColor: 'rgba(13, 113, 205, 0.08)',
  },
  offerImageStyle: {
    width: wp('9%'),
    height: hp('4.5%'),
  },
  offerTextTitle: {
    fontSize: RFValue(12),
    color: '#3D3D3D',
    fontFamily: fonts.medium,
    width: wp("40%")
  },
  offerSubTitle: {
    fontSize: RFValue(10),
    marginTop: hp('0.5%'),
    color: '#3D3D3D',
    fontFamily: fonts.regular,
    width: wp("40%")
  },

  restaurantDetails: {
    backgroundColor: '#FFFFFF',
    marginTop: hp('2%'),
    width: wp('90%'),
    alignSelf: 'center',
    elevation: 10,
    padding: hp('1.5%'),
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    shadowOffset: { width: 2, height: 4 },
    shadowColor: '#171717',
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  listConatiner: {
    backgroundColor: '#FFFFFF',
    width: wp('100%'),
    padding: hp('2%'),
    // shadowOffset: { width: 2, height: 4 },
    // alignItems:"center",
    // shadowColor: '#171717',
    // shadowOpacity: 0.2,
    // shadowRadius: 3,
  },

  offTextView: {
    backgroundColor: '#F9BD00',
    position: 'absolute',
    padding: 4,
    width: wp('22%'),
    borderRadius: 8,
    bottom:'-4%',
    right: '14%'
  },
  offText: {
    textAlign: 'center',
    fontFamily: fonts.medium,
    fontSize: RFValue(12)
    , color: '#FFFFFF'
  },
  // dottedLine: {
  //   borderStyle: 'dotted',
  //   borderWidth: 2,
  //   borderRadius: 1,
  //   marginLeft: hp('1%'),
  //   marginRight: hp('1%'),
  //   marginTop: hp('2.5%'),
  //   borderColor: '#D9D9D9',
  // },
  homeDottedStyle: {
    borderStyle: 'dotted',
    borderWidth: 1,
    borderRadius: 1,
    borderColor: '#D9D9D9',
  },
  menuOptionConatiner: {
    position: 'absolute',
    bottom: hp('3'),
    alignSelf: 'center',
    shadowOpacity: 0.2,
    shadowOffset: { width: -2, height: 4 },
    shadowColor: '#171717',
    flexDirection: 'row',
    shadowRadius: 3,
  },
  menuConatiner: {
    backgroundColor: 'black',
    paddingLeft: hp('1%'),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingRight: hp('1%'),
    borderRadius: 10,
    paddingTop: hp('0.5%'),
    paddingBottom: hp('0.5%'),
  },
  menuText: {
    color: 'white',
    fontFamily: fonts.semiBold,
    fontSize: RFValue(12),
    marginRight: hp('0.5%'),
  },
  vegConatiner: {
    borderRadius: 6,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingLeft: hp('1%'),
    paddingRight: hp('1%'),
    paddingTop: hp('0.7%'),
    paddingBottom: hp('0.7%'),
    borderWidth: 0.3,
    borderWidth: 0.5,
    shadowOffset: { width: -2, height: 4 },
    shadowColor: '#171717',
  },
  restaurantSubConatiner: {
    justifyContent: 'space-between',
    marginTop: hp('0.3%'),
    marginBottom: hp('0.5%'),
  },
  resturantTitle: {
    fontFamily: fonts.semiBold,
    color: colors.black,
    fontSize: RFValue(16),
  },
  restaurantSpecialityConatainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginTop: hp('1%'),
    width: wp('85%'),
  },
  restaurantSpecialityText: {
    fontSize: RFValue(11),
    marginTop: hp('0%'),
    color: '#646464',
    width: wp('50%'),
    fontFamily: fonts.regular,
  },
  restaurantlocationConatainer: {
    backgroundColor: 'rgba(13, 113, 205, 0.1)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(13, 113, 205, 0.5)',
    paddingTop: hp('0.3%'),
    paddingBottom: hp('0.3%'),
    paddingLeft: hp('1%'),
    paddingRight: hp('0.3%'),
    width: wp('35%'),
    alignSelf: 'center',
  },
  restaurantaddressStyle: {
    color: '#0D71CD',
    fontFamily: fonts.medium,
    fontSize: RFValue(9),
    width: wp('28%'),
  },
  restaurantRatingConatiner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: hp('1%'),
    width: wp('85%'),
  },
  restaurantRatingSub: {
    backgroundColor: '#F9BD00',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: hp('0.5%'),
    paddingRight: hp('0.5%'),
    paddingTop: hp('0.3%'),
    paddingBottom: hp('0.3%'),
    borderRadius: 6,
  },
  restaurnatratingText: {
    color: '#FFFFFF',
    fontSize: RFValue(12),
    fontFamily: fonts.medium,
    padding: hp('0.5%'),
  },
  restaurantReview: {
    color: '#646464',
    fontSize: RFValue(12),
    fontFamily: fonts.medium,
  },
  restuarnatTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: wp('40%'),
    alignSelf: 'center',
    justifyContent: 'flex-end',
  },
  restaurantTime: {
    color: '#646464',
    fontSize: RFValue(10),
    fontFamily: fonts.regular,
  },
  restaurantTimeSpace: {
    marginLeft: hp('0.6%'),
    marginRight: hp('0.6%'),
    fontFamily: fonts.regular,
  },
  restaurantDistance: {
    color: '#646464',
    fontFamily: fonts.regular,
    fontSize: RFValue(10),
  },

  noDataView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop:hp('25%')
  },
  noDataText: {
    fontSize: RFValue(14),
    fontFamily: fonts.medium,
    color:colors.black,
  },

  restaurantMenuSelector: {
    flexDirection: 'row',
    width: wp('90%'),
    alignSelf: 'center',
    marginTop: hp('2%'),
    alignItems: 'flex-start',
    marginBottom: hp('2%'),
  },
  restaurantmenuText: {
    fontSize: RFValue(12),
    fontFamily: fonts.semiBold,
    color: 'black',
    textAlign: 'center',
    marginLeft: hp('0.8%'),
  },
  restaurantNonVegText: {},
  restuarnatVegConatiner: {
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingLeft: hp('1%'),
    paddingRight: hp('1%'),
    paddingTop: hp('0.7%'),
    paddingBottom: hp('0.7%'),
    shadowOffset: { width: -2, height: 4 },
    shadowColor: '#171717',
    shadowOpacity: 0.2,
    borderWidth: 0.3,
    borderWidth: 0.5,
    shadowRadius: 3,
  },
  restaurantNonVegConatiner: {
    borderRadius: 6,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingLeft: hp('1%'),
    paddingRight: hp('1%'),
    paddingTop: hp('0.7%'),
    paddingBottom: hp('0.7%'),
    marginLeft: '2%',
    borderWidth: 0.3,
    borderWidth: 0.5,
    shadowOffset: { width: -2, height: 4 },
    shadowColor: '#171717',
  },
  restuarantListImage: {
    height: hp('13%'),
    width: wp('30%'),
    borderColor: '#0D71CD',
    borderWidth: 0.2,
    borderRadius: 10,
  },
  restaurantDiscountConatiner: {
    position: 'absolute',
    backgroundColor: '#0D71CD',
    height: hp('3.5%'),
    bottom: hp('-1.25%'),
    paddingHorizontal: 10,
    borderRadius: 6,

    padding: 6,
    alignSelf: 'center',
  },
  restaurantDiscountText: {
    color: '#FFFFFF',
    fontFamily: fonts.regular,
    fontSize: RFValue(12),
  },
  restaurantBestConatiner: {
    borderRadius: 4,
    marginLeft: 5,
    backgroundColor: '#F07300',
    alignItems: 'center',
    justifyContent: 'center',
  },
  restauranttypeText: {
    fontSize: RFValue(9),
    fontFamily: fonts.medium,
    color: '#FFFFFF',
  },
  restuarantItemConatiner: {
    marginTop: hp('1.2%'),
    color: 'black',
    fontFamily: fonts.semiBold,
    fontSize: RFValue(16),
    width: wp('55%'),
  },
  restuarantItemName: {
    color: '#333333',
    fontSize: RFValue(13),
    fontFamily: fonts.semiBold,
  },
  restaurnatItemDetails: {
    color: 'grey',
    fontFamily: fonts.semiBold,
    fontSize: RFValue(11),
  },
  restaurantPriceCoantiner: {
    marginTop: hp('1%'),
    alignItems: 'center',
    width: wp('55%'),
    alignSelf: 'center',
  },
  restaurantPriceSub: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginTop:'-2%'
  },
  restaurantPriceTextt: {
    color: '#1D721E',
    fontFamily: fonts.semiBold,
    fontSize: RFValue(14),
  },
  restaurnatQunatityConatiner: {
    flexDirection: 'row',
    borderRadius: 8,
    backgroundColor: '#1D721E',
    borderColor: '#1D721E',
    width: wp('25%'),
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    padding: '3%'
  },
  addBox: {
    flexDirection: 'row',
    borderRadius: 8,
    backgroundColor: '#1D721E',
    borderColor: '#1D721E',
    paddingHorizontal: hp('1.5%'),
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'space-evenly',
     padding: '10%'
  },
  addText: {
    fontSize: RFValue(14),
    color: '#FFFFFF',
    fontFamily: fonts.semiBold,
  },

  CartConatiner: {
    backgroundColor: '#f2797f',
    alignSelf: 'center',
    position: 'absolute',
    width: wp('50%'),
    alignItems: 'center',
    bottom: 10,
    padding: hp('1.5%'),
    borderRadius: 10,
  },
  cartTextConatiner: {
    color: 'white',
    fontFamily: fonts.bold,
    fontSize: RFValue(14),
  },
  orderConatiner: {
    width: wp('100%'),
    height: hp('100%'),
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  cancelIcon: {
    marginBottom: hp('2%'),
    backgroundColor: 'black',
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    alignSelf: 'center',
  },
  orderConatinerr: {
    width: wp('100%'),
    height: hp('60%'),
    backgroundColor: 'white',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  orderImage: {
    width: '90%',
    height: hp('22%'),
    alignSelf: 'center',
    borderRadius: 8,
  },
  categoryOrderImage: {
    marginTop: hp('0.5%'),
    height: hp('20%'),
    width: wp('90%'),
    borderRadius: 15,
  },

  orderType: {
    borderRadius: 4,

    backgroundColor: '#F07300',
    alignItems: 'center',
    width: wp('20%'),
    justifyContent: 'center',
    marginLeft: '5%',
    fontSize: RFValue(12),
    backgroundColor: 'orange',
    color: 'white',
    textAlign: 'center',
    marginTop: hp('1.5%'),
    padding: 1,
  },
  orderText: {
    marginLeft: '5%',
    fontSize: RFValue(12),
    padding: 2,

    fontFamily: fonts.medium,
    color: '#FFFFFF',
  },
  orderDescriptionConatiner: {
    width: '90%',
    alignSelf: 'center',

  },
  orderItemDescription: {
    color: 'black',
    fontFamily: fonts.regular,
  },
  orderReview: {
    marginTop: hp('0.3%'),
    color: '#8F8F8F',
    width: wp('70%'),
    fontSize: RFValue(12),
    fontFamily: fonts.regular,
  },
  dishDescription: {
    color: 'grey',
    fontFamily: fonts.regular,
    fontSize: RFValue(12),
  },
  dishItemConatiner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: hp('2%'),
  },
  dishSubConatiner: {
    flexDirection: 'row',
    borderRadius: 10,
    backgroundColor: '#1D721E',
    borderColor: '#1D721E',
    width: wp('25%'),
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    height:hp('5.5%')
    // padding: hp('0.8%'),
  },
  menuOrderContainer: {
    width: wp('100%'),
    height: hp('100%'),
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  menuModal: {
    marginBottom: hp('2%'),
    backgroundColor: 'black',
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    alignSelf: 'center',
  },
  menuModalContainer: {
    width: wp('100%'),
    height: hp('60%'),
    backgroundColor: '#fff',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    paddingBottom: '5%',
  },
  menuModalSub: {
    paddingLeft: hp('2%'),
    paddingRight: hp('2%'),
    marginTop: hp('2%'),
  },
  menuTextStyle: {
    fontSize: RFValue(16),
    fontFamily: fonts.semiBold,
  },
  menuCategoryText: {
    fontSize: RFValue(14),
    fontFamily: fonts.regular,
    marginTop: hp('1%'),
    color: 'black',
  },
  orderCustomizationConatiner: {
    padding: hp('2%'),
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  filterConatiner: {
    height: 20,
    width: 20,
    borderWidth: 1,
    borderRadius: 6,
  },
  padding: {
    marginLeft: hp('1.5%'),
    marginRight: hp('1.5%'),
  },
});

export { restuarantStyles };
