export default {
    // Base_Url :'https://duuitt.hashsoft.io/',
    // Image_Url :'https://duuitt.hashsoft.io/',

    // Base_Url :'https://duuitt.hsdevbox.com/',
    // Image_Url :'https://duuitt.hsdevbox.com/',

    Base_Url: 'https://duuitt.hashsoftware.com/',
    Image_Url: 'https://duuitt.hashsoftware.com/',

    login: 'customers',
    verifyOtp: 'customers/verify-otp',
    forgetPass: 'customers/forget-password',
    resendOtp: 'customers/send-otp',
    updatePassword: 'customers/update-password',
    myAddress: 'customers/address',
    getMyAddress: 'customers/detail',
    parcelsRides: 'orders',
    editParcelsRides: "orders/update-order-details",
    parcels_Cancel: 'orders/cancel',
    parcels_find_rider: 'orders/find-rider',
    updateProfile: 'customers/update-profile',
    parcelsOfUser: 'orders/ofuser',
    ordersRecentOrder: 'orders/recent-order',
    ordersTrackOrder: 'orders/track-order',
    pendingForCustomer: 'orders/pending-for-customer',
    customersFcmToken: 'customers/update',
    testMessage: 'test/message',
    updateOrderStatus: 'orders/update-order-status',

    restaurentAll: 'restaurant/all',
    allDishCategory: 'dish-category/all',
    restaurantListaccordingCategory: 'restaurant/restaurant-list-for-menu-group',
    // restaurantUnderMenuGroup:'restaurant/menu-item-under-menu-group',
    restaurantUnderMenuGroup: 'food-item/of-menu-group-list',//
    restaurantListForDishCategory: 'restaurant/restaurant-list-for-dish-category',//
    restaurantCustomerLikeDislike: 'restaurant/customer-like-dislike',
    restaurantLikedByCustomer: 'restaurant/liked-by-customer',
    setCart: 'cart',
    updateCart: 'cart/update',
    getCart: 'cart/get',
    deleteCart: 'cart/delete',
    foodOrder: 'food-order',
    repeatedOrderList: 'food-order/repeated-order-list',
    recomendedItems: 'food-order/recomended-items',
    getFoodOrderTracking: 'food-order/get-tracking-order',
    addReviews: 'reviews',
    completeMealItems: 'food-item/complete-your-meal-items',
    restaurantReview: 'reviews/restaurant-review',
    // restaurantOffers:'offers/all'
    restaurantOffers: 'offers/recomended-offer',
    restaurantOffersData:'cart/customer-offers',
    applyCoupon: 'cart/apply-coupon',
    appFeedback: 'orders/app-feedback',


    wallet: 'wallet',
    walletUpdateBalance: "wallet/update-balance",
    paymentsCreateOrder: 'payments/create-order',
    paymentsVerify: 'payments/verify',
    deleteAccount: 'customers/info',
    adminInfo: 'admin/info',
    supportInfo: 'contact',
    updateCustomerInfo: 'customers/update-customer-info',
    checkDeviceId: "customers/check-device-info",

    sendMessage: "chat/send-message",
    markSeen: "chat/mark-seen",
    chatOrderId: "chat",
    unseenMessages: 'chat/unseen-messages',
    updateOrderArrivedTime: "orders/update-order-arrived-time",
    userLogout: "customers/logout",

}

